### ISSUE TITLE
Implement header component of news-stand

### ISSUE THREAD

**Issue by hjsong333** [hjsong333/fe-max--newsstand#1]
## Summary
Create and render header component of news-stand

## Desscription
Header component has news-stand brand mark on left side. On the other side, date information should be displayed.

## Subtasks
- [x] Create element and append child elements
- [x] Define and invoke function for current date information in header component
- [x] Append header element to root element of page
- [x] Work on layout of header component

**Comment by hjsong333** [comment]
fc22c4a4614846f5253809fbd7758228eb955f0d all substasks are done
