### ISSUE TITLE
Subscribe and cancel subscription

### ISSUE THREAD

**Issue by hjsong333** [hjsong333/fe-max--newsstand#13]
## Summary
Feature that subscribe media or cancel subscription of media.

## Subtasks
- [ ] Send request to server.
- [ ] Render result of subscription.
- [ ] Preventing excessive events for request.
- [ ] Adding a modal dialog for confirmation.
