### ISSUE TITLE
Rolling headline news

### ISSUE THREAD

**Issue by hjsong333** [hjsong333/fe-max--newsstand#14]
## Summary
Roll up headline news automatically.

## Description
- Each headline should work independently. 
- Each headline's interval has gap of 1second.
- Interval for rolling event is 3 seconds.
- Pausing the rolling interval when the mouse hovers.

## Subtasks
- [x] Render headline news with fetched data.
- [x] Render both current and next news.
- [x] Roll up news wrapper every 3 seconds.

**Comment by hjsong333** [comment]
ad29273053d64f777c4b6c075887137488810667
