### ISSUE TITLE
Add page refresh on logo click

### ISSUE THREAD

**Issue by hjsong333** [hjsong333/fe-max--newsstand#3]
## Summary
Refresh current page when click the logo in header component.

## Subtasks
- [x] change tag of logo
- [x] add handler for click event to logo element
- [x] anchor tag styling(remove text-decoration and change color to black)

**Comment by hjsong333** [comment]
27c39fc8ab10284e00ba52d58931b87fb8774852 
Implement feature is succeeded. 

But, anchor tag's color is not removed by normalize. So, anchor tag styling is neccessary.

**Comment by hjsong333** [comment]
8b2f5766f36fe553f9274c8346f995be021348cf
Removal of text-decoration and changing text color to black is completed.
