### ISSUE TITLE
Implement and render auto rolling news bar component

### ISSUE THREAD

**Issue by hjsong333** [hjsong333/fe-max--newsstand#4]
## Summary
Create rolling news bar component and display it under header.

## Subtasks
- [x] Create news bar element
- [x] Create child element of news bar
- [x] Append children to news bar element
- [x] Append news bar on the news stand element

**Comment by hjsong333** [comment]
Actually, news bar should have two rolling news components.
So, this structure may be right.
```
news stand ─ news bar ┬ rolling news
                      └ rolling news
```

**Comment by hjsong333** [comment]
eefd7ba61b129cf5c01e7ca9b02a7b6bf0f6d483
Task is completed
