### ISSUE TITLE
Grid view for entire media

### ISSUE THREAD

**Issue by hjsong333** [hjsong333/fe-max--newsstand#6]
## Summary
View of main component for the entire press in grid view.

## Subtasks
- [x] Create 6 * 4 tables in an area of 930px width and 388px height.
- [x] Place the brand mark of the media company in the center of each table cell.
- [x] Arranges arrows to turn pages on the left and right of the grid.
- [x] Implement random arrange brand marks when the page is refreshed.
- [x] #9

**Comment by hjsong333** [comment]
ab2f57464e256020047119767c5a9e4b686203fa 
Create GridView component and render it without style code. This code contains just pure table element contain dummy data to check rendering.

**Comment by hjsong333** [comment]
f8b9df53422ca0a28059076783a128bc2da20421
Layout for GridView is finished.
Adjust cell size and image position with image source from naver news-stand('한국경제').

**Comment by hjsong333** [comment]
8afcbe58c0789bf2394f58138329e602ded124a5
Render actual logo image in GridView. Image source url was from news-stand of portal site.

**Comment by hjsong333** [comment]
9376235d6852a4e76c2282d673c63ed2141a5430
Implementation of arrows that flip page of GridView is completed. 🐬

**Comment by hjsong333** [comment]
36a1acd4bd1faf76e5281361d7289c57c756d2c4
Random shuffle of media logos is implemented. Fisher-Yates algorithm is applied on it. 🔀 

Here is log why I introduce Fisher-Yates algorithm on it.
### 혼자 생각한 방식

GPT나 검색의 도움을 받기 전 시도한 방식

```jsx
const gridImgs = [];
while (gridData.length > 0) {
  gridImgs.push(...gridData.splice(gridData.length * Math.random(), 1));
}
```

랜덤 인덱스에 해당하는 요소를 빼서 새로운 요소에 넣고, 남은 요소가 없어질 때까지 이 과정을 반복한다.

이렇게 얻은 배열로 새로고침 때마다 그리드 뷰의 브랜드마크 순서를 랜덤하게 바꾸는 기능을 구현했다. 결과는 성공적이다.

### GPT에게 물어본 방식: Fisher-Yates 알고리즘

혼자서 생각한 방식이 얼마나 효율적인지 비교를 통해 알아보기로 했다.

GPT가 추천해준 방식은 Fisher-Yates 알고리즘이라고 불린다.

```jsx
function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1)); // 0부터 i까지의 랜덤 인덱스 선택
    [array[i], array[j]] = [array[j], array[i]]; // 요소 위치 교환
  }
  return array;
}
```

이 방식은 새로운 배열을 생성하지 않고 요소들을 교체하면서 섞어준다. 새로운 배열을 생성하지 않아서 메모리 낭비가 적고 splice로 발생하는 검색도 적어서 효율이 좋다고 생각한다.

GPT에게 비교를 의뢰하니 splice() 메서드로 요소를 제거하면 배열의 재정렬과 재할당이 발생한다고 한다. 배열의 크기가 크다면 성능에 큰 영향을 줄거라고 한다. 반면, Fisher-Yates 알고리즘의 방식은 배열의 크기와 무관하게 일관된 성능을 보장한다고 한다.

**Comment by hjsong333** [comment]
To render different text '구독하기' and '해지하기', I need subsribed id list of media. Then I can check subscribed media or not.
