### ISSUE TITLE
Implement main component with header

### ISSUE THREAD

**Issue by hjsong333** [hjsong333/fe-max--newsstand#7]
## Summary
Create main component element and render it with children of it.

## Description
Main component has header containing tabs and view icons in it.

## Subtasks
- [x] Create Main component
- [x] Create MainHeader component
- [x] Implement tabs and view icons on MainHeader
- [x] Basic layout work based on Figma design

**Comment by hjsong333** [comment]
c19e3631ebf571bba0f0aae9278b7d0959fe162a Implement Main and MainHeader Component without layout

**Comment by hjsong333** [comment]
4fa68486af1befcc8300e307636897338c6c08b9 Layout for MainHeader

**Comment by hjsong333** [comment]
In MainHeader, too many properties are involved. 
Considering future enhancements, component separation seems necessary.

**Comment by hjsong333** [comment]
Anyway, task is completed
